[package]
name = "stm32l031x"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[build-dependencies]
bobbin-chip = { path = "../../../bobbin-chip/" }

[dependencies]
bobbin-common = { path = "../../bobbin-common" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }

[features]

stm32l031x4 = []
stm32l031x6 = []