[package]
name = "%name%"
version = "0.1.0"

[dependencies]
bobbin-chip-common = { path = "../../bobbin-chip-common" }
bobbin-cortexm = { path = "../../bobbin-dev/mcu/bobbin-cortexm" }
stm32-common = { path = "../../bobbin-dev/mcu/bobbin-stm32/stm32-common" }
