[package]
name = "kl26"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../bobbin-build/" }

[dependencies]
kinetis-common = { path = "../kinetis-common" }

[features]
default = []

Z128 = []
Z64 = []
