[package]
name = "stm32l432x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
bobbin-bits = "0.1.1"
bobbin-mcu = { path = "../../../lib/bobbin-mcu" }
bobbin-hal = { path = "../../../lib/bobbin-hal" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32L432xB = []
STM32L432xC = []
