[package]
name = "stm32f302x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32F302K6 = []
STM32F302K8 = []
STM32F302C6 = []
STM32F302C8 = []
STM32F302R6 = []
STM32F302R8 = []
