[package]
name = "frdm-k64f"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[dependencies.cortex-m-rt]
features = []
version = "0.4.0"

[dependencies.log]
version = "0.4"
default-features = false

[profile.dev]
panic = "abort"
opt-level = "s"
codegen-units = 1
incremental = false
lto = true
debug = false

[profile.release]
panic = "abort"
debug = true
lto = true

[dev-dependencies]
examples = { path = "../../apps/examples" }
embedded-hal = "0.1.2"

[dependencies.k64]
path = "../../mcu/bobbin-kinetis/k64"
features = ["K64FN1M0"]

