[package]
name = "stm32f10x"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[build-dependencies]
bobbin-chip = { path = "../../../bobbin-chip/" }

[dependencies]
bobbin-common = { path = "../../bobbin-common" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32F103x8 = []
STM32F103xB = []