[package]
name = "%name%"
version = "0.1.0"

[dependencies]
bobbin-bits = "0.1.1"
bobbin-mcu = { path = "../../lib/bobbin-mcu" }
bobbin-hal = { path = "../../lib/bobbin-hal" }

[features]
default = []
