[package]
name = "samd21"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[dependencies]
samd21-chip = { path = "../samd21-chip" }
samd21-hal = { path = "../samd21-hal" }

[features]
SAMD21G18 = ["samd21-chip/SAMD21G18"]