[package]
name = "stm32f40x"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[dependencies]
stm32f40x-chip = { path = "../stm32f40x-chip" }
stm32f40x-hal = { path = "../stm32f40x-hal" }

[features]
STM32F405xE = ["stm32f40x-chip/STM32F405xE"]
STM32F405xG = ["stm32f40x-chip/STM32F405xG"]
STM32F407xE = ["stm32f40x-chip/STM32F407xE"]
STM32F407xG = ["stm32f40x-chip/STM32F407xG"]
STM32F415xG = ["stm32f40x-chip/STM32F415xG"]
STM32F417xE = ["stm32f40x-chip/STM32F415xE"]
STM32F417xG = ["stm32f40x-chip/STM32F415xG"]

