[package]
name = "stm32f42x-chip"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]
build = "build.rs"

[lib]
path = "src/lib.rs"

[build-dependencies]
bobbin-chip = { path = "../../../bobbin-chip/" }

[dependencies]
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32F427VG = []
STM32F427VI = []
STM32F429VE = []
STM32F429VG = []
STM32F429VI = []
STM32F427ZG = []
STM32F427ZI = []
STM32F429ZE = []
STM32F429ZG = []
STM32F429ZI = []
STM32F427AG = []
STM32F427AI = []
STM32F429AG = []
STM32F429AI = []
STM32F427IG = []
STM32F427II = []
STM32F429IE = []
STM32F429IG = []
STM32F429II = []
STM32F429BE = []
STM32F429BG = []
STM32F429BI = []
STM32F429NE = []
STM32F429NG = []
STM32F429NI = []
