[package]
name = "apollo2"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[build-dependencies]
bobbin-build = { path = "../../bobbin-build/" }

[dependencies]
bobbin-common = { path = "../../bobbin-common" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["mem","c"]

[features]
AMAPH1KK = []