[workspace]
members = [
    "bobbin-cortexm",
    "bobbin-kinetis/*/",
    "bobbin-sam/*/",
    "bobbin-stm32/*/",
]

exclude = [
    "bobbin-kinetis/target/",
    "bobbin-sam/target/",
    "bobbin-stm32/target/",
]
