[package]
name = "discovery-stm32f3"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[dependencies.cortex-m-rt]
features = []
version = "0.3.13"

[dependencies.log]
version = "0.3"
default-features = false

[profile.dev]
panic = "abort"
opt-level = "s"
codegen-units = 1
incremental = false
lto = true

[profile.release]
panic = "abort"
debug = true
lto = true


[dependencies.stm32f3x]
path = "../../mcu/bobbin-stm32/stm32f303x"
features = ["STM32F303xC"]

