[package]
name = "stm32f20x"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[build-dependencies]
bobbin-chip = { path = "../../../bobbin-chip/" }

[dependencies]
bobbin-common = { path = "../../bobbin-common" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32F205RB = []
STM32F205RC = []
STM32F205RE = []
STM32F205RF = []
STM32F205RG = []
STM32F205VB = []
STM32F205VC = []
STM32F205VE = []
STM32F205VF = []
STM32F205VG = []
STM32F205ZC = []
STM32F205ZE = []
STM32F205ZF = []
STM32F205ZG = []
STM32F207VC = []
STM32F207VE = []
STM32F207VF = []
STM32F207VG = []
STM32F207ZC = []
STM32F207ZE = []
STM32F207ZF = []
STM32F207ZG = []
STM32F207IC = []
STM32F207IE = []
STM32F207IF = []
STM32F207IG = []