[package]
name = "stm32f10x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32F103x8 = []
STM32F103xB = []
