[package]
name = "stm32f303x"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[dependencies]
stm32f303x-chip = { path = "../stm32f303x-chip" }
stm32f303x-hal = { path = "../stm32f303x-hal" }

[features]
default = []
stm32f303rdx = ["stm32f303x-chip/stm32f303rdx"]
stm32f303rex = ["stm32f303x-chip/stm32f303rex"]
stm32f303vdx = ["stm32f303x-chip/stm32f303vdx"]
stm32f303vex = ["stm32f303x-chip/stm32f303vex"]
stm32f303zdx = ["stm32f303x-chip/stm32f303zdx"]
stm32f303zex = ["stm32f303x-chip/stm32f303zex"]