[package]
name = "stm32f303x-chip"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]
build = "build.rs"

[lib]
path = "src/lib.rs"

[build-dependencies]
bobbin-chip = { path = "../../bobbin-chip/" }

[dependencies]
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }

[features]
default = []

stm32f303rdx = []
stm32f303rex = []
stm32f303vdx = []
stm32f303vex = []
stm32f303zdx = []
stm32f303zex = []