[package]
name = "%name%"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
bobbin-hal = { path = "../../../lib/bobbin-hal/" }
sam-common = { path = "../sam-common" }

[features]
default = []
