[package]
name = "%name%"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../bobbin-build/" }

[dependencies]
sam-common = { path = "../sam-common" }

[features]
default = []
