[workspace]
members = [
    "stm32-common", 
    "stm32f303x", "stm32f303x-chip", "stm32f303x-hal",
    "stm32f42x", "stm32f42x-chip", "stm32f42x-hal", 
    "stm32l031x", "stm32l031x-chip", "stm32l031x-hal"
    ]