[package]
name = "stm32f3x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
stm32-common = { path = "../stm32-common" }

[features]
default = []
logger = ["stm32-common/logger"]

STM32F303xB = []
STM32F303xC = []
STM32F303xD = []
STM32F303xE = []
