[package]
name = "stm32f20x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32F20xB = []
STM32F20xC = []
STM32F20xE = []
STM32F20xF = []
STM32F20xG = []
