[package]
name = "bobbin-common"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[dependencies]
bobbin-bits = "0.1.0"
bobbin-hz = { path = "../bobbin-hz" }
bobbin-tree = { path = "../bobbin-tree" }
