[package]
name = "stm32f10x-hal"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[dependencies]
bobbin-common = { path = "../../bobbin-common" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }
stm32f10x-chip = { path = "../stm32f10x-chip" }