[package]
name = "nucleo-f746zg"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[dependencies.cortex-m-rt]
features = []
version = "0.4.0"

[dependencies.bobbin-sys]
path = " ../../../../lib/bobbin-sys/"

# [dependencies.bobbin-hal]
# path = " ../../../../lib/bobbin-hal/"

# [dependencies.bobbin-mcu]
# path = " ../../../../lib/bobbin-mcu/"


[dev-dependencies]
examples = { path = "../../apps/examples" }
embedded-hal = "0.1.2"

[profile.dev]
panic = "abort"
opt-level = "s"
incremental = false
lto = true

[profile.release]
panic = "abort"
debug = true
lto = true


[dependencies.stm32f74x]
path = "../../mcu/bobbin-stm32/stm32f74x"
features = ["STM32F74xxG"]

