[package]
name = "kinetis-common"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]
build = "build.rs"

[build-dependencies]
bobbin-chip = { path = "../../../bobbin-chip/" }

[dependencies]
bobbin-common = { path = "../../bobbin-common" }