[package]
name = "%name%"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
bobbin-bits = "0.1.1"
bobbin-mcu = { path = "../../../lib/bobbin-mcu" }
bobbin-hal = { path = "../../../lib/bobbin-hal" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }
kinetis-common = { path = "../kinetis-common" }

[features]
default = []
