[package]
authors = ["Andrey Tkachenko <andreytkachenko64@gmail.com>"]
name = "discovery-stm32f429i"
version = "0.1.0"
[dependencies]
cortex-m = "0.5.2"
cortex-m-rt = "0.5.1"
embedded-hal = "0.2.1"
panic-abort = "0.2.0"

[dependencies.stm32f42x]
features = ["STM32F42xxI"]
path = "../../mcu/bobbin-stm32/stm32f42x"

[dev-dependencies.examples]
path = "../../app/examples"

[lib]
