[package]
name = "arduino-zero"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[dependencies.cortex-m-rt]
features = []
version = "0.3.13"

[profile.dev]
panic = "abort"
opt-level = "s"
codegen-units = 1
incremental = false
lto = true

[profile.release]
panic = "abort"
debug = true
lto = true

[dev-dependencies]
examples = { path = "../../apps/examples" }

[dependencies.samd21]
path = "../../mcu/bobbin-sam/samd21"
features = ["SAMD21x18"]

