[package]
name = "stm32f40x-chip"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]
build = "build.rs"

[lib]
path = "src/lib.rs"

[build-dependencies]
bobbin-chip = { path = "../../../bobbin-chip/" }

[dependencies]
bobbin-common = { path = "../../bobbin-common" }
bobbin-cortexm = { path = "../../bobbin-cortexm" }
stm32-common = { path = "../stm32-common" }

[features]
STM32F405xE = []
STM32F405xG = []
STM32F407xE = []
STM32F407xG = []
STM32F415xG = []
STM32F417xE = []
STM32F417xG = []