[package]
name = "bobbin-chip"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[dependencies]
clap = "2.*"
error-chain = "0.10"
bobbin-sexp = { path = "../bobbin-sexp/sexp" }
bobbin-sexp-tokenizer = { path = "../bobbin-sexp/sexp-tokenizer" }
