[package]
name = "audio-node"
version = "0.1.0"
authors = ["Jonathan Soo <jcsoo@agora.com>"]

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[dependencies]
stm32l4x2 = { path = "../../mcu/bobbin-stm32/stm32l4x2"}
r0 = "0.1.0"

[features]
default = ["stm32l4x2/stm32l462xE"]

[profile.dev]
panic = "abort"
opt-level = "s"
lto = false

[profile.release]
panic = "abort"
debug = true
lto = true